#!/bin/sh

# this script determines a list of all gateway servers configured on a node 
# and tries to upload its fastd key to each of those servers by calling the
# script upload_key_to_server
 
path="$( dirname "$0" )"

WGETC=$(which wget)

MAC=$(sed 's/://g' /lib/gluon/core/sysconfig/primary_mac)
KEY=$(/etc/init.d/fastd show_key mesh_vpn)

uci show fastd | grep remote | cut -d"=" -f2 | sed -e 's/\"//g' | cut -d " " -f1 | while read HOST; do
  $WGETC -O - -q "http://${HOST}/upload_key?mac=${MAC}&key=${KEY}" &>/dev/null
done

exit 0
