#!/bin/sh

# this script will upload the nodes fastd key to the gateway server
# provided as the first argument ($1)

UPLOAD_URL=$1
WGETC=$(which wget)

MAC=$(sed 's/://g' /lib/gluon/core/sysconfig/primary_mac)
KEY=$(/etc/init.d/fastd show_key mesh_vpn)

$WGETC -O - -q "$UPLOAD_URL/upload_key?mac=${MAC}&key=${KEY}" &>/dev/null

exit 0
