#!/usr/bin/lua

local site = require 'gluon.site_config'
local uci = require('luci.model.uci').cursor()


uci:foreach('wireless', 'wifi-iface', function(s)
    if string.match(s['.name'], '^alias_.*') then
        uci:delete('wireless', s['.name'])
    end
end)

uci:save('wireless')
uci:save('network')
uci:commit('wireless')
uci:commit('network')
